'use client';

import './globals.css';

import { Inter } from 'next/font/google';

import { HeaderBox } from './components/UI/Header/Header.component';

import StyledJsxRegistry from './registry'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderBox />
        <StyledJsxRegistry>{children}</StyledJsxRegistry>
        </body>
    </html>
  )
}
